### PR TITLE
m2ua/m2pa: Speculative change to add m2ua/m2pa decoding from hep

### PR DESCRIPTION
**Pull request by zecke**
Attempt to handle m2ua/m2pa payloads in HEP. This has not been
tested with any trace yet.

### CODE REVIEW

**Comment by zecke** [comment]
@adubovikov THIS HAS NOT BEEN TESTED AT ALL. So please review carefully. :)

**Comment by adubovikov** [comment]
for me it looks good...
@giavac  can you check also ?

**Comment by zecke** [comment]
It doesn't work and I have a trace to test with now. :)

**Comment by giavac** [comment]
@zecke what's the status of this PR, please? Was the issue in Wireshark fixed, and if yes from which version? Thank you.

**Comment by zecke** [comment]
* Please merge it.
* Wireshark fix is in version 2.4 or later.

**Review by giavac — APPROVED** [review]
I've verified it doesn't break some reference captures I have, so happy to merge. Thanks.

**Comment by zecke** [comment]
*yeah*

**Pull request merged**
